export const PLANS = [
    {
        name: "Monthly",
        anotherName: 'Yearly',
        price: " ",
        checkBox: 'checkBox',
        features: [
            "Calendar notifications",
            "Calendar connections",
            "Notes history",
            "Integrations",
            "Auto-join meetings",
            "Al Notes",
            "Al Notes templates",
            "Remove Zoom and Slack branding",
        ],
    },
    {
        name: "Free",
        price: "$0",
        month: '',
        button: <button>Try for Free</button>,
        features: [
            "done",
            "1",
            "1 month",
            "email , slack",
            "-",
            "-",
            "-",
            "-",
        ],
    },
    {
        name: "Basic",
        price: "$25",
        month: '/mo',
        button: <button>Try for Free</button>,

        features: [
            "done",
            "Unlimited",
            "Unlimited",
            "Notion, Google Drive",
            "done",
            "10/month",
            "-",
            "done",
        ],
    },
    {
        name: "Pro",
        price: "$50",
        month: '/mo',
        button: <button>Try for Free</button>,
        features: [
            "done",
            "Unlimited",
            "Unlimited",
            "+Salesforce, Hubspot, Zapier",
            "done",
            "Unlimited",
            "-",
            "done",
        ],
    },
];
