import { IoHome } from "react-icons/io5";
import { IoIosArrowForward } from "react-icons/io";
import { MdOutlineDone } from "react-icons/md";
import 'aos/dist/aos.css';

import  style from './style.module.css'
import {useEffect} from "react";
import AOS from "aos";

const WhyLexxi = () => {
    useEffect(() => {
        AOS.init({
            duration: 1000
        });
    }, []);

    return (
          <div className={style.whyLexxi}>
               <div className={style.whyLexxiIcons}>
                    <IoHome  size={24} color={'white'}/>
                    <IoIosArrowForward size={18} color={'white'}/>
                   <p>Ai Meeting</p>
               </div>

              <div className={style.main}>
                  <div  className={style.mainLeft}>
                          <h1>Improve your productivity with AI-meetings</h1>
                          <p> <MdOutlineDone size={24} color={'green'}/> <span>A new era of productivity and efficiency</span> </p>
                          <p> <MdOutlineDone size={24} color={'green'}/> <span>Simplify and optimize your meetings with AI</span></p>
                  </div>
                  <div className={style.mainRight}  >
                       <img src='https://images.ctfassets.net/z2yjrn4ew0rg/2u0kGs32oYNXC5xd08ufVQ/cbe24e50e0228753d38e8d15ea2f0ac7/home_image.png?w=800' />
                  </div>

              </div>
             <div className={style.flipBlock}>
                <div className={style.flip} data-aos="flip-left">
                  AI meetings automate note-taking and generate intelligent summaries,
                 simplifying meetings and promoting communication, collaboration and decision-making.
                </div>
             </div>
              <div className={style.fadeBlock}>
                  <div className={style.fadeRight} data-aos="fade-up-right">
                      <div>
                          <h2>AI meeting at Leexi</h2>
                          <div>
                             <div className={style.Info}>
                                 <div>
                                 <MdOutlineDone size={24} color={'white'}/>
                                 </div>
                                 <span>
                                     With AI meeting, you automatically receive a
                                     summary of your video conferences and telephone calls.
                                 </span>
                             </div>
                              <div className={style.Info}>
                                  <div>
                                      <MdOutlineDone size={24} color={'white'}/>
                                  </div>
                                  <span>
                                      AI-meetings increase productivity,
                                      and Leexi goes further than the summary:
                                      you'll also receive action points,
                                      a follow-up email generated by artificial intelligence and more.
                                 </span>
                              </div>
                          </div>
                      </div>


                  </div>
                  <div className={style.fadeLeft} data-aos="fade-up-left">
                      <div>
                         <img   src='https://images.ctfassets.net/z2yjrn4ew0rg/RNLNW3nvHNwCTK9MS2xXf/aeafaad4346c90c9190827a0fb41dbb7/ordi.png?w=1000' />
                      </div>
                  </div>
              </div>
          </div>
     )
}

export default  WhyLexxi
